### ISSUE TITLE
PushGateway Limitations

### ISSUE THREAD

**Issue by saikovvuri** [mkjoerg/nifi-prometheus-reporter#22]
Hello - this is more of a question. 

What are your thoughts on - https://prometheus.io/docs/practices/pushing/

Thanks

**Comment by containerpope** [comment]
Pushgateway is not best practice if it is possible in your Infra to fetch metrics by Prometheus. Due to the fact, that it was simpler to implement and there is no interface for scraping metrics by Prometheus in Nifi, we chose the Pushgateway approach.

**Comment by saikovvuri** [comment]
Thanks for the response.  So in our scenario , we are sending Nifi Metrics to PushGateway and then use Telegraf agent to scrape data from PushGateway endpoint   Any advise on if there are better options, all we need is something that Telegraf can scrape the data.

**Comment by containerpope** [comment]
I have no further experience with Telegraf, maybe there are some other Nifi reporting Tasks that provide metrics for this?

If you want to stick with the Nifi prometheus reporting task, it is necessary to use the Pushgateway in between, due to the fact, that the library is written exclusively for this. After the Pushgatway you can scrape with every technology that is able to read from there.

**Comment by saikovvuri** [comment]
Thanks ,  that is how we have implemented for now ,  Telegraf scraping data from pushgateway.

**Comment by containerpope** [comment]
Do you have any further questions? If not, could you close this issue ? :)
