### ISSUE TITLE
Contribute to Apache NiFi

### ISSUE THREAD

**Issue by JPercivall** [mkjoerg/nifi-prometheus-reporter#9]
Given the friendly ASLv2 license and the code quality, it would be nice to contribute this back to Apache NiFi as a built-in reporting task (for this ticket[1]). Of course, the preferable way to add Prometheus functionality to NiFi would be to add the /metrics endpoint[2] but this is a good way to add the functionality without modifying the core API.

[1] https://issues.apache.org/jira/browse/NIFI-4362
[2] https://issues.apache.org/jira/browse/NIFI-5435

**Comment by containerpope** [comment]
Maybe a good idea. In our use case this was just something missing in Nifi at this time.

**Comment by aramatev** [comment]
Why not enable SSL, why only auth ? Isn't a secure connection more important than login ?

**Comment by containerpope** [comment]
It depends on the use case. Actually ssl wasn‘t necessary in our use case
at all, because we deployed a pushgateway on the same pods(inside
kubernetes as sidecar). There was actually no traffic to the outside world,
just localhost. But the pushgateway has authentication enabled and a
loadbalancer with ssl termination in front of it if we would have needed an
external connection.
If you need ssl enabled, feel free to create a PR :)

**Comment by containerpope** [comment]
We proposed it to nifi team.
